name: Get Changed Files
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setip-python@v3
        with:
          python-version: 3.9
          

        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for changed_file in ${{ steps.files.outputs.all }}; 
          do
            echo "Change File Log"
            echo "Do something with this ${changed_file}."
            done
