# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main
 paths:
  exclude:
    - cicd/*
    - .github/*  
  

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevBuild
    jobs:
      - job: PrintVaribles
        steps:
          - script: |
              echo "$(System.DefinitionId)"
              echo "$(Build.BuildNumber)"
              echo "$(Build.ArtifactStagingDirectory)"
              echo "$(Build.SourceVersion)"
    
      - job: RunScript
        steps:
          - script: |
              python -m pip install --upgrade pip
              python install -r cicd/requirement.txt
          - task: PythonScript@0
            inputs:
              scriptSource: 'filePath'
              scriptPath: $(System.DefaultWorkingDirectory)/cicd/databricks_steps.py
          - script: echo DEV Job Run