# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main
 paths:
  exclude:
    - cicd/*
    - .github/*  
  

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevBuild
    jobs:
      # - job: PrintVaribles
      #   steps:
      #     - script: |
      #         echo "$(System.DefinitionId)"
      #         echo "$(Build.BuildNumber)"
      #         echo "$(Build.ArtifactStagingDirectory)"
      #         echo "$(Build.SourceVersion)"

      #         commit_id=$(Build.SourceVersion)
      #         commit_id=${commit_id:0:7}

      #         echo "commid id:$commit_id"
      - job: cicd_deployment
        steps:
          - task: Bash@3
            displayName: "Print Variables"
            inputs:
              script: |
                echo "$(System.DefinitionId)"
                echo "$(Build.BuildNumber)"
                echo "$(Build.ArtifactStagingDirectory)"
                echo "$(Build.SourceVersion)"

                commit_id=$(Build.SourceVersion)
                commit_id=${commit_id:0:7}

                echo "commid id:$commit_id"
          - task: Bash@3
            displayName: "git diff command"
            inputs:
              script: |
                commit_id=$(Build.SourceVersion)
                commit_id=${commit_id:0:7}

                git diff-tree --no-commit-id --name-status -m -r "$commit_id" > $(Build.ArtifactStagingDirectory)/change_log.csv

                echo "list of changed files saved to output/drop/change_log.csv"
              
      # - job: RunScript
      #   steps:
      #     - script: |
      #         python -m pip install --upgrade pip
      #         echo "Successfully Updated PIP"
      #         pip install -r $(System.DefaultWorkingDirectory)/cicd/requirement.txt
      #         echo "Installation is completd for the libraries"
      #     - task: PythonScript@0
      #       inputs:
      #         scriptSource: 'filePath'
      #         scriptPath: $(System.DefaultWorkingDirectory)/cicd/databricks_steps.py
      #     - script: echo DEV Job Run