name: Get Changed Files
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            format: 'csv'
      - name: Get changed files

        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for changed_file in ${{ steps.files.outputs.all }}; 
          do
            echo "Do something with this ${changed_file}."
            done
