name: Run Tests on Push



on:

  push:

    branches: [ main ]



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run Tests

        run: | 

          # Assuming your YAML file is called "test_config.yaml" in the root directory

          yaml_path="./yaml/list_all_variables.yml"

          # Execute your test command using the YAML path

          pytest --config $yaml_path
