name: List and filter variables

on:
  push:
    branches:
      - main

jobs:
  listAndFilterVariables:
    runs-on: ubuntu-latest
    steps:
      - name: List variables
        run: |
          echo "All variables"
          env
          echo "Filtered variables"
          env | grep GITHUB
