name: Checkout Branch Test

on:
  pull_request:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        run: |
          echo $GITHUB_WORKSPACE

      - name: List All variables
        run: |
          echo "List all the variables"
          echo "Base Ref: ${{github.base_ref}}"
          echo "Base Head: ${{github.head_ref}}"
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
      - name: Changed file name
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"

