name: Checkout Branch Test

on:
  pull_request:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        run: |
          echo $GITHUB_WORKSPACE

      - name: List All variables
        run: |
          echo "List all the variables"
          echo "Base Ref: ${{github.base_ref}}"
          echo "Base Head: ${{github.head_ref}}"

      - id: Files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
            if changed_file[-4:]=="json"
              echo "Do something with this ${changed_file}."

          done
