name: Checkout Branch Test

on:
  pull_request:
    branches: 
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        run: |
          echo $GITHUB_WORKSPACE

      - name: List All variables
        run: |
          echo "List all the variables"
          echo "Base Ref: ${{github.base_ref}}"
          echo "Base Head: ${{github.head_ref}}"

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cicd/requirement.txt
          echo "All the required Library Install"
        
      # - name: Run Python Script
      #   run: |
      #     python ./pyspark/python_script.py
      - name: Fetch all branches
        run: git fetch --all

      - name: List all branches
        run: git branch -a
      
      - name: Change Log CSV FILE
        run: |
          git diff --name-status origin/${{github.base_ref}}..origin/${{github.head_ref}} > ${{github.workspace}}/cicd/change_log.csv
          echo "Run Python Script and read the change_log.csv file"
          # After using git fetch --all this line started working.

          python ./pyspark/python_script.py 
        env:
          CONTEXT_VARS: ${{toJson(vars)}}
        
     
